version: "3"

tasks:
  docs:start:
    summary: "Calls yarn start in docs directory"
    cmds:
      - yarn start
    silent: true
    dir: docs

  chain:serve:
    summary: Serve the blockchain using Ignite
    cmds:
      - ignite chain serve
    silent: true

  build:
    deps:
      - build:cli
      - build:hubd
      - build:git-remote-pfg
    silent: false

  build:cli:
    cmds:
      - sudo go build -o /usr/local/bin/peerforge-cli cmd/peerforge-cli/*
    silent: false

  build:hubd:
    cmds:
      - sudo go build -o /usr/local/bin/hubd cmd/peerforge-hubd/*
    silent: false

  build:git-remote-pfg:
      cmds:
        - sudo go build -o /usr/local/bin/git-remote-pfg cmd/git-remote-pfg/*
      silent: false